image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
    - init: |
        cp .env.example .env;
        pipenv install;
        mysql -u root -e "CREATE DATABASE example";
        pipenv run flask db init;
        pipenv run flask db migrate;
        pipenv run flask db upgrade;
      command: >
        pipenv run python src/app.py;
