"""empty message

Revision ID: dc109a4288c4
Revises: 
Create Date: 2020-09-15 15:44:17.559160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc109a4288c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('clients_id', sa.Integer(), nullable=False),
    sa.Column('clients_name', sa.String(length=300), nullable=False),
    sa.Column('clients_rut', sa.String(length=16), nullable=False),
    sa.Column('clients_nationality', sa.String(length=300), nullable=True),
    sa.Column('clients_civilStatus', sa.String(length=300), nullable=True),
    sa.Column('clients_job', sa.String(length=300), nullable=True),
    sa.Column('clients_address', sa.String(length=300), nullable=True),
    sa.Column('clients_contact', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('clients_id'),
    sa.UniqueConstraint('clients_name'),
    sa.UniqueConstraint('clients_rut')
    )
    op.create_table('lawyers',
    sa.Column('lawyers_id', sa.Integer(), nullable=False),
    sa.Column('lawyers_name', sa.String(length=300), nullable=False),
    sa.Column('lawyers_field', sa.String(length=300), nullable=False),
    sa.Column('lawyers_rut', sa.String(length=300), nullable=False),
    sa.Column('lawyers_password', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('lawyers_id'),
    sa.UniqueConstraint('lawyers_name'),
    sa.UniqueConstraint('lawyers_rut')
    )
    op.create_table('cases',
    sa.Column('cases_id', sa.Integer(), nullable=False),
    sa.Column('cases_description', sa.String(length=300), nullable=False),
    sa.Column('cases_rol_rit_ruc', sa.String(length=300), nullable=True),
    sa.Column('cases_trial_entity', sa.String(length=300), nullable=False),
    sa.Column('cases_legalIssue', sa.String(length=300), nullable=True),
    sa.Column('cases_procedure', sa.String(length=300), nullable=True),
    sa.Column('cases_objetive', sa.String(length=300), nullable=False),
    sa.Column('cases_update', sa.String(length=300), nullable=True),
    sa.Column('cases_pendingTask', sa.String(length=300), nullable=True),
    sa.Column('cases_updateDate', sa.DateTime(), nullable=True),
    sa.Column('cases_activeCase', sa.Boolean(), nullable=True),
    sa.Column('cases_incomeDate', sa.DateTime(), nullable=False),
    sa.Column('cases_deadLine', sa.DateTime(), nullable=True),
    sa.Column('cases_client_id', sa.Integer(), nullable=False),
    sa.Column('cases_lawyer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cases_client_id'], ['clients.clients_id'], ),
    sa.ForeignKeyConstraint(['cases_lawyer_id'], ['lawyers.lawyers_id'], ),
    sa.PrimaryKeyConstraint('cases_id')
    )
    op.create_table('corporations',
    sa.Column('corporation_id', sa.Integer(), nullable=False),
    sa.Column('corporation_name', sa.String(length=300), nullable=False),
    sa.Column('corporation_type', sa.String(length=300), nullable=True),
    sa.Column('corporation_CBR', sa.String(length=300), nullable=False),
    sa.Column('corporation_rolSII', sa.String(length=300), nullable=True),
    sa.Column('corporation_taxType', sa.String(length=300), nullable=True),
    sa.Column('corporation_client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corporation_client_id'], ['clients.clients_id'], ),
    sa.PrimaryKeyConstraint('corporation_id')
    )
    op.create_table('documents',
    sa.Column('documents_id', sa.Integer(), nullable=False),
    sa.Column('documents_type', sa.String(length=100), nullable=True),
    sa.Column('documents_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('documents_cases_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['documents_cases_id'], ['cases.cases_id'], ),
    sa.PrimaryKeyConstraint('documents_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_table('corporations')
    op.drop_table('cases')
    op.drop_table('lawyers')
    op.drop_table('clients')
    # ### end Alembic commands ###
